### ISSUE TITLE
Do you have plan about PPLNS too?

### ISSUE THREAD

**Issue by ahonder** [flexpool/solo#1]
Hi,
first i will try when you complete SOLO code. And curiosly about pplns too. watching your project.

Thanks for your effort!!!

**Comment by AlexSSD7** [comment]
Hi, glad that you asked!

This project is more like a mining proxy, not like a pool. It does not distribute payments across the miners and is intended to be used only by one miner.

And why do you need PPLNS when you have a full-featured and scalable Flexpool?

**Comment by ahonder** [comment]
thanks for fast reply,
some miners requesting pplns too (p.s my prefer is solo). have a little pool (oep based ETC pool) and mining with a few friends. 
asking PPLNS too because some miners requesting SOLO some miners requesting PPLNS payment scheme.  I'm looked up to  https://flexpool.io/(PPLNS right?). looking very nice frontend, amazing. And readed somewhere from your pages 100TH/s capable for one pool and this incredible.

waiting your amazing effort results. and ps every developer adding donation account to code, you must be too.
