### ISSUE TITLE
Using as proxy only

### ISSUE THREAD

**Issue by pool2mine** [flexpool/solo#3]
hi, i know this is an issue tracker, but i was wondering if you can tell me if this works as stratum proxy to point all my miners to another pool? i'm currently mining in my own pool but i can't find other updated stratum proxy project, all of them has 5+ years. please let me know. thanks!

**Comment by AlexSSD7** [comment]
Hi! Thanks for asking.
This project is an extended proxy that wraps node getWork to a miner-recognizable stratum protocol. Unfortunately, it does not support pointing rigs to another pool.
