### ISSUE TITLE
build problem 

### ISSUE THREAD

**Issue by maxinsur** [flexpool/solo#5]
......
[3/4] Linking dependencies...
warning " > sass-loader@9.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
[4/4] Building fresh packages...
error /src/app/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /src/app/node_modules/node-sass
Output:
Building: /usr/local/bin/node /src/app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/src/app/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@15.1.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/src/app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/src/app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/src/app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /src/app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /src/app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /src/app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/src/app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/src/app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/src/app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /src/app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /src/app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /src/app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/src/app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/src/app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/src/app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /src/app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /src/app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /src/app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:183:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/src/app/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/src/app/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/src/app/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /src/app/node_modules/which/which.js:89:16
gyp verb `which` failed     at /src/app/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /src/app/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/src/app/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/src/app/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/src/app/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/src/app/node_modules/which/which.js:80:29)
gyp ERR! stack     at /src/app/node_modules/which/which.js:89:16
gyp ERR! stack     at /src/app/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /src/app/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:183:21)
gyp ERR! System Linux 5.4.0-51-generic
gyp ERR! command "/usr/local/bin/node" "/src/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /src/app/node_modules/node-sass
gyp ERR! node -v v15.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install && yarn build' returned a non-zero code: 1
make: *** [Makefile:18: docker-image] Error 1

i update sass-loader, webpack, phyton and so on, but...

**Comment by AlexSSD7** [comment]
Hello. This project is no longer maintained due to no funding.
